/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test;

import connection.ExcuteSQLStatement;
import java.awt.Dimension;
import java.awt.*;
import java.awt.HeadlessException;
import java.io.File;
import java.util.ArrayList;
import model.DishesButton;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import static view.QuanlyThucDon.nguyenLieuSua;
import static view.QuanlyThucDon.suaNguyenLieu_jList;
import static view.QuanlyThucDon.suaShowNguyenLieu_jTextArea;
import view.WrapLayout;

/**
 *
 * @author jiang
 */
public final class QuanLyThucDonJPanel extends javax.swing.JPanel {

    private final ArrayList<DishesButton1> listMonAn = new ArrayList<>();
    public static int trangThaiChonXoaOrSua = 0; // 0:Huy; 1:Xoa; 2:Sua 
    private final ArrayList<String> nguyenLieuDaChon = new ArrayList<>();
    public static int themOrXoaNguyenLieu = 0; //0: Khong co j; 1:Xoa; 2:Them
    public static ArrayList<String> nguyenLieuSua;
    public static ArrayList<JPanel> loaiMonAnJPanels = new ArrayList<>();

    /**
     * Creates new form QuanLyThucDonJPanel
     */
    public QuanLyThucDonJPanel() {
        initComponents();
        showMonAnTuDataBase();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        themMonAn_jDialog = new javax.swing.JDialog();
        themMaMonaAn_jLabel = new javax.swing.JLabel();
        themMaMonAn_jTextField = new javax.swing.JTextField();
        themAnhMonAnTuFile_jButton = new javax.swing.JButton();
        themTenMonAn_jTextField = new javax.swing.JTextField();
        themTenMon_jLabel = new javax.swing.JLabel();
        confirmThemMonAn_jButton = new javax.swing.JButton();
        themLoaiMonAn_jLabel = new javax.swing.JLabel();
        themLoaiMonAn_jComboBox = new javax.swing.JComboBox<>();
        themAnhMonAn_jLabel = new javax.swing.JLabel();
        cancel_themMonAn_jButton = new javax.swing.JButton();
        themPathAnhMonAn_jTextField = new javax.swing.JTextField();
        themDonGia_jLabel = new javax.swing.JLabel();
        themDonGia_jTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        themNguyenLieu_jList = new javax.swing.JList<>();
        confirmThemNguyenLieu_jButton = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        themShowNguyenLieuDaChon_jTextArea = new javax.swing.JTextArea();
        confirmThemMonAn_jOptionPane = new javax.swing.JOptionPane();
        themMonAn_jFileChooser = new javax.swing.JFileChooser();
        xoa_suaMonAn_jDialog = new javax.swing.JDialog();
        suaMaMonAn_jLabel = new javax.swing.JLabel();
        suaMaMonAn_jTextField = new javax.swing.JTextField();
        suaTenMon_jLabel = new javax.swing.JLabel();
        suaTenMonAn_jTextField = new javax.swing.JTextField();
        suaLoaiMonAn_jLabel = new javax.swing.JLabel();
        suaLoaiMonAn_jComboBox = new javax.swing.JComboBox<>();
        suaAnhMonAn_jLabel = new javax.swing.JLabel();
        suaPathAnhMonAn_jTextField = new javax.swing.JTextField();
        suaAnhMonAnTuFile_jButton = new javax.swing.JButton();
        confirmSuaMonAn_jButton = new javax.swing.JButton();
        cancel_xoa_suaMonAn_jButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        suaNguyenLieu_jList = new javax.swing.JList<>();
        suaDonGia_jLabel = new javax.swing.JLabel();
        suaDonGia_jTextField = new javax.swing.JTextField();
        suaNguyenLieu_jLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        suaShowNguyenLieu_jTextArea = new javax.swing.JTextArea();
        confirmSuaNguyenLieu_jButton = new javax.swing.JButton();
        confirmXoaNguyenLieu_jButton = new javax.swing.JButton();
        suaTinhTrangMonAn_jLabel = new javax.swing.JLabel();
        suaTinhTrangMonAn_jComboBox = new javax.swing.JComboBox<>();
        xoa_suaMonAn_jOptionPane = new javax.swing.JOptionPane();
        themLoaiMonAn_jDialog = new javax.swing.JDialog();
        themTenLoaiMonAn_jLabel = new javax.swing.JLabel();
        themTenLoaiMonAn_jTextField = new javax.swing.JTextField();
        themMoTaLoaiMonAn_jLabel = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        themMoTaLoaiMonAn_jTextArea = new javax.swing.JTextArea();
        confirmThemLoaiMonAn_jButton = new javax.swing.JButton();
        cancelThemLoaiMonAn_jButton = new javax.swing.JButton();
        suaLoaiMonAn_jDialog = new javax.swing.JDialog();
        suaChonLoaiMonAn_jLabel = new javax.swing.JLabel();
        suaChonLoaiMonAn_jComboBox = new javax.swing.JComboBox<>();
        chonMonAnCanSua_jButton = new javax.swing.JButton();
        tenMoiLoaiMonAn_jLabel = new javax.swing.JLabel();
        tenMoiLoaiMonAn_jTextField = new javax.swing.JTextField();
        moTaMoiLoaiMonAn_jLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        moTaMoiLoaiMonAn_jTextArea = new javax.swing.JTextArea();
        cancelSuaLoaiMonAn_jButton = new javax.swing.JButton();
        comfirmSuaLoaiMonAn_jButton = new javax.swing.JButton();
        tenMoiLoaiMonAn_jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        quanLyThucDon_jPanel = new javax.swing.JPanel();
        searchMonAnTheo_jComboBox = new javax.swing.JComboBox<>();
        themMonAn_jButton = new javax.swing.JButton();
        searchMonAn_jPanel = new javax.swing.JPanel();
        searchMonAn_jTextField = new javax.swing.JTextField();
        searchMonAn_jButton1 = new javax.swing.JButton();
        themLoaiMonAn_jButton = new javax.swing.JButton();
        suaLoaiMonAn_jButton = new javax.swing.JButton();
        showMonAn_jTabbedPane = new javax.swing.JTabbedPane();

        themMonAn_jDialog.setTitle("Thêm món ăn");
        themMonAn_jDialog.setModal(true);
        themMonAn_jDialog.setResizable(false);

        themMaMonaAn_jLabel.setText("Mã món ăn");

        themMaMonAn_jTextField.setEnabled(false);

        themAnhMonAnTuFile_jButton.setText("Browse");
        themAnhMonAnTuFile_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themAnhMonAnTuFile_jButtonActionPerformed(evt);
            }
        });

        themTenMonAn_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themTenMonAn_jTextFieldActionPerformed(evt);
            }
        });

        themTenMon_jLabel.setText("Tên món");

        confirmThemMonAn_jButton.setText("Xác Nhận");
        confirmThemMonAn_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmThemMonAn_jButtonActionPerformed(evt);
            }
        });

        themLoaiMonAn_jLabel.setText("Loại món ăn");

        ArrayList<String> StrTenLMA = new ArrayList<String>();
        String[] arrTenLMA = chonThongTinLoaiMonAn(StrTenLMA);
        for (int i=0; i <arrTenLMA.length; i++){
            themLoaiMonAn_jComboBox.addItem(arrTenLMA[i]);
        }

        themAnhMonAn_jLabel.setText("Chọn ảnh món ăn");

        cancel_themMonAn_jButton.setText("Hủy");
        cancel_themMonAn_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_themMonAn_jButtonActionPerformed(evt);
            }
        });

        themPathAnhMonAn_jTextField.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        themPathAnhMonAn_jTextField.setText("Path...");
        themPathAnhMonAn_jTextField.setEnabled(false);

        themDonGia_jLabel.setText("Đơn giá (VNĐ)");

        jLabel2.setText("Nguyên liệu");

        ArrayList<String> StrTenNL = new ArrayList<String>();
        String[] arrTenNL = chonTenNguyenLieu(StrTenNL);
        themNguyenLieu_jList = new javax.swing.JList(arrTenNL);
        themNguyenLieu_jList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane7.setViewportView(themNguyenLieu_jList);

        confirmThemNguyenLieu_jButton.setText("Thêm nguyên liệu");
        confirmThemNguyenLieu_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmThemNguyenLieu_jButtonActionPerformed(evt);
            }
        });

        themShowNguyenLieuDaChon_jTextArea.setColumns(20);
        themShowNguyenLieuDaChon_jTextArea.setRows(5);
        themShowNguyenLieuDaChon_jTextArea.setFocusable(false);
        jScrollPane8.setViewportView(themShowNguyenLieuDaChon_jTextArea);

        javax.swing.GroupLayout themMonAn_jDialogLayout = new javax.swing.GroupLayout(themMonAn_jDialog.getContentPane());
        themMonAn_jDialog.getContentPane().setLayout(themMonAn_jDialogLayout);
        themMonAn_jDialogLayout.setHorizontalGroup(
            themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themMonAn_jDialogLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(themMonAn_jDialogLayout.createSequentialGroup()
                            .addGroup(themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(themMaMonaAn_jLabel)
                                .addComponent(themLoaiMonAn_jLabel)
                                .addComponent(themMaMonAn_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(themTenMon_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(themTenMonAn_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(themLoaiMonAn_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(themAnhMonAn_jLabel)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, themMonAn_jDialogLayout.createSequentialGroup()
                            .addComponent(cancel_themMonAn_jButton)
                            .addGap(107, 107, 107))
                        .addGroup(themMonAn_jDialogLayout.createSequentialGroup()
                            .addComponent(themPathAnhMonAn_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(themAnhMonAnTuFile_jButton)))
                    .addComponent(themDonGia_jLabel)
                    .addComponent(jLabel2)
                    .addGroup(themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, themMonAn_jDialogLayout.createSequentialGroup()
                            .addGroup(themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(confirmThemNguyenLieu_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane8))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(themDonGia_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmThemMonAn_jButton))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        themMonAn_jDialogLayout.setVerticalGroup(
            themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themMonAn_jDialogLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themMaMonaAn_jLabel)
                    .addComponent(themTenMon_jLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themMaMonAn_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(themTenMonAn_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(themLoaiMonAn_jLabel)
                .addGap(18, 18, 18)
                .addComponent(themLoaiMonAn_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(themAnhMonAn_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themPathAnhMonAn_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(themAnhMonAnTuFile_jButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(themDonGia_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themDonGia_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(themMonAn_jDialogLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmThemNguyenLieu_jButton))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_themMonAn_jButton)
                    .addComponent(confirmThemMonAn_jButton))
                .addGap(15, 15, 15))
        );

        themMonAn_jFileChooser.addChoosableFileFilter(new FileNameExtensionFilter("*.png", "png"));
        themMonAn_jFileChooser.addChoosableFileFilter(new FileNameExtensionFilter("*.jpg", "jpg"));

        xoa_suaMonAn_jDialog.setTitle("Xóa, sửa món ăn");
        xoa_suaMonAn_jDialog.setModal(true);
        xoa_suaMonAn_jDialog.setResizable(false);

        suaMaMonAn_jLabel.setText("Mã món ăn");

        suaMaMonAn_jTextField.setEnabled(false);

        suaTenMon_jLabel.setText("Tên món");

        suaLoaiMonAn_jLabel.setText("Loại món ăn");

        suaLoaiMonAn_jComboBox.setModel(themLoaiMonAn_jComboBox.getModel());

        suaAnhMonAn_jLabel.setText("Chọn ảnh món ăn");

        suaPathAnhMonAn_jTextField.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        suaPathAnhMonAn_jTextField.setText("Path...");
        suaPathAnhMonAn_jTextField.setEnabled(false);

        suaAnhMonAnTuFile_jButton.setText("Browse");
        suaAnhMonAnTuFile_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaAnhMonAnTuFile_jButtonActionPerformed(evt);
            }
        });

        confirmSuaMonAn_jButton.setText("Sửa");
        confirmSuaMonAn_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmSuaMonAn_jButtonActionPerformed(evt);
            }
        });

        cancel_xoa_suaMonAn_jButton.setText("Hủy");
        cancel_xoa_suaMonAn_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_xoa_suaMonAn_jButtonActionPerformed(evt);
            }
        });

        suaNguyenLieu_jList.setModel(themNguyenLieu_jList.getModel());
        jScrollPane1.setViewportView(suaNguyenLieu_jList);

        suaDonGia_jLabel.setText("Đơn giá (VNĐ)");

        suaNguyenLieu_jLabel.setText("Nguyên liệu");

        suaShowNguyenLieu_jTextArea.setEditable(false);
        suaShowNguyenLieu_jTextArea.setColumns(20);
        suaShowNguyenLieu_jTextArea.setRows(5);
        jScrollPane2.setViewportView(suaShowNguyenLieu_jTextArea);

        confirmSuaNguyenLieu_jButton.setText("Thêm");
        confirmSuaNguyenLieu_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmSuaNguyenLieu_jButtonActionPerformed(evt);
            }
        });

        confirmXoaNguyenLieu_jButton.setText("Xóa");
        confirmXoaNguyenLieu_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmXoaNguyenLieu_jButtonActionPerformed(evt);
            }
        });

        suaTinhTrangMonAn_jLabel.setText("Tình trạng món:");

        suaTinhTrangMonAn_jComboBox.setModel(themLoaiMonAn_jComboBox.getModel());

        javax.swing.GroupLayout xoa_suaMonAn_jDialogLayout = new javax.swing.GroupLayout(xoa_suaMonAn_jDialog.getContentPane());
        xoa_suaMonAn_jDialog.getContentPane().setLayout(xoa_suaMonAn_jDialogLayout);
        xoa_suaMonAn_jDialogLayout.setHorizontalGroup(
            xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xoa_suaMonAn_jDialogLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(xoa_suaMonAn_jDialogLayout.createSequentialGroup()
                        .addGroup(xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(suaNguyenLieu_jLabel)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(xoa_suaMonAn_jDialogLayout.createSequentialGroup()
                                .addComponent(confirmXoaNguyenLieu_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmSuaNguyenLieu_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xoa_suaMonAn_jDialogLayout.createSequentialGroup()
                                .addComponent(cancel_xoa_suaMonAn_jButton)
                                .addGap(26, 26, 26)
                                .addComponent(confirmSuaMonAn_jButton))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(suaAnhMonAn_jLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suaDonGia_jLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suaDonGia_jTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, xoa_suaMonAn_jDialogLayout.createSequentialGroup()
                        .addComponent(suaPathAnhMonAn_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suaAnhMonAnTuFile_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, xoa_suaMonAn_jDialogLayout.createSequentialGroup()
                        .addGroup(xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(suaLoaiMonAn_jComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(suaMaMonAn_jTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(suaMaMonAn_jLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(suaLoaiMonAn_jLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(suaTinhTrangMonAn_jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(suaTenMonAn_jTextField)
                            .addGroup(xoa_suaMonAn_jDialogLayout.createSequentialGroup()
                                .addGroup(xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(suaTenMon_jLabel)
                                    .addComponent(suaTinhTrangMonAn_jLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        xoa_suaMonAn_jDialogLayout.setVerticalGroup(
            xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xoa_suaMonAn_jDialogLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(xoa_suaMonAn_jDialogLayout.createSequentialGroup()
                        .addGroup(xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(suaMaMonAn_jLabel)
                            .addComponent(suaTenMon_jLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(suaMaMonAn_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suaTenMonAn_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(suaLoaiMonAn_jLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suaLoaiMonAn_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(xoa_suaMonAn_jDialogLayout.createSequentialGroup()
                        .addComponent(suaTinhTrangMonAn_jLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suaTinhTrangMonAn_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(suaAnhMonAn_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suaAnhMonAnTuFile_jButton)
                    .addComponent(suaPathAnhMonAn_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(suaDonGia_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suaDonGia_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(suaNguyenLieu_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(xoa_suaMonAn_jDialogLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confirmSuaNguyenLieu_jButton)
                            .addComponent(confirmXoaNguyenLieu_jButton)))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmSuaMonAn_jButton)
                    .addComponent(cancel_xoa_suaMonAn_jButton))
                .addGap(20, 20, 20))
        );

        xoa_suaMonAn_jOptionPane.setMessageType(2);
        xoa_suaMonAn_jOptionPane.setOptionType(0);

        themLoaiMonAn_jDialog.setTitle("Thêm loại món ăn");
        themLoaiMonAn_jDialog.setResizable(false);

        themTenLoaiMonAn_jLabel.setText("Tên loại món ăn");

        themMoTaLoaiMonAn_jLabel.setText("Mô tả");

        themMoTaLoaiMonAn_jTextArea.setColumns(20);
        themMoTaLoaiMonAn_jTextArea.setRows(5);
        jScrollPane9.setViewportView(themMoTaLoaiMonAn_jTextArea);

        confirmThemLoaiMonAn_jButton.setText("Xác nhận");
        confirmThemLoaiMonAn_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmThemLoaiMonAn_jButtonActionPerformed(evt);
            }
        });

        cancelThemLoaiMonAn_jButton.setText("Hủy");
        cancelThemLoaiMonAn_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelThemLoaiMonAn_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout themLoaiMonAn_jDialogLayout = new javax.swing.GroupLayout(themLoaiMonAn_jDialog.getContentPane());
        themLoaiMonAn_jDialog.getContentPane().setLayout(themLoaiMonAn_jDialogLayout);
        themLoaiMonAn_jDialogLayout.setHorizontalGroup(
            themLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themLoaiMonAn_jDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(themLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(themLoaiMonAn_jDialogLayout.createSequentialGroup()
                        .addComponent(themMoTaLoaiMonAn_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, themLoaiMonAn_jDialogLayout.createSequentialGroup()
                        .addGroup(themLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane9)
                            .addGroup(themLoaiMonAn_jDialogLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(themLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(themLoaiMonAn_jDialogLayout.createSequentialGroup()
                                        .addComponent(cancelThemLoaiMonAn_jButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(confirmThemLoaiMonAn_jButton))
                                    .addGroup(themLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(themTenLoaiMonAn_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                                        .addComponent(themTenLoaiMonAn_jTextField)))))
                        .addGap(10, 10, 10))))
        );
        themLoaiMonAn_jDialogLayout.setVerticalGroup(
            themLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themLoaiMonAn_jDialogLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(themTenLoaiMonAn_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themTenLoaiMonAn_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(themMoTaLoaiMonAn_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(themLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmThemLoaiMonAn_jButton)
                    .addComponent(cancelThemLoaiMonAn_jButton))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        suaLoaiMonAn_jDialog.setResizable(false);

        suaChonLoaiMonAn_jLabel.setText("Chọn loại món ăn");

        suaChonLoaiMonAn_jComboBox.setModel(themLoaiMonAn_jComboBox.getModel());

        chonMonAnCanSua_jButton.setText("Chọn");
        chonMonAnCanSua_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonMonAnCanSua_jButtonActionPerformed(evt);
            }
        });

        tenMoiLoaiMonAn_jLabel.setText("Tên mới cho loại món ăn");

        moTaMoiLoaiMonAn_jLabel.setText("Mô tả mới của loại món ăn");

        moTaMoiLoaiMonAn_jTextArea.setColumns(20);
        moTaMoiLoaiMonAn_jTextArea.setRows(5);
        jScrollPane3.setViewportView(moTaMoiLoaiMonAn_jTextArea);

        cancelSuaLoaiMonAn_jButton.setText("Hủy");
        cancelSuaLoaiMonAn_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSuaLoaiMonAn_jButtonActionPerformed(evt);
            }
        });

        comfirmSuaLoaiMonAn_jButton.setText("Sửa");
        comfirmSuaLoaiMonAn_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comfirmSuaLoaiMonAn_jButtonActionPerformed(evt);
            }
        });

        tenMoiLoaiMonAn_jLabel1.setText("Tên mới cho loại món ăn");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout suaLoaiMonAn_jDialogLayout = new javax.swing.GroupLayout(suaLoaiMonAn_jDialog.getContentPane());
        suaLoaiMonAn_jDialog.getContentPane().setLayout(suaLoaiMonAn_jDialogLayout);
        suaLoaiMonAn_jDialogLayout.setHorizontalGroup(
            suaLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suaLoaiMonAn_jDialogLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(suaLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suaLoaiMonAn_jDialogLayout.createSequentialGroup()
                        .addGroup(suaLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(suaChonLoaiMonAn_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suaLoaiMonAn_jDialogLayout.createSequentialGroup()
                                .addComponent(suaChonLoaiMonAn_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chonMonAnCanSua_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                .addGap(11, 11, 11)))
                        .addContainerGap())
                    .addGroup(suaLoaiMonAn_jDialogLayout.createSequentialGroup()
                        .addGroup(suaLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(suaLoaiMonAn_jDialogLayout.createSequentialGroup()
                                .addComponent(cancelSuaLoaiMonAn_jButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comfirmSuaLoaiMonAn_jButton))
                            .addGroup(suaLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, suaLoaiMonAn_jDialogLayout.createSequentialGroup()
                                    .addComponent(tenMoiLoaiMonAn_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)
                                    .addGroup(suaLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tenMoiLoaiMonAn_jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(tenMoiLoaiMonAn_jTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(suaLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                .addComponent(moTaMoiLoaiMonAn_jLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        suaLoaiMonAn_jDialogLayout.setVerticalGroup(
            suaLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suaLoaiMonAn_jDialogLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(suaChonLoaiMonAn_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(suaLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suaChonLoaiMonAn_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chonMonAnCanSua_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(suaLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(suaLoaiMonAn_jDialogLayout.createSequentialGroup()
                        .addComponent(tenMoiLoaiMonAn_jLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(suaLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenMoiLoaiMonAn_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(suaLoaiMonAn_jDialogLayout.createSequentialGroup()
                        .addComponent(tenMoiLoaiMonAn_jLabel1)
                        .addGap(28, 28, 28)))
                .addGap(12, 12, 12)
                .addComponent(moTaMoiLoaiMonAn_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(suaLoaiMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comfirmSuaLoaiMonAn_jButton)
                    .addComponent(cancelSuaLoaiMonAn_jButton))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        quanLyThucDon_jPanel.setLayout(new WrapLayout(FlowLayout.LEFT));
        quanLyThucDon_jPanel.setSize(new Dimension(630, 1));
        quanLyThucDon_jPanel.setBackground(new java.awt.Color(220, 249, 247));
        quanLyThucDon_jPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(250, 300, 250, 300));
        quanLyThucDon_jPanel.setPreferredSize(new java.awt.Dimension(900, 600));
        quanLyThucDon_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchMonAnTheo_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo tên món ăn", "Theo loại món ăn" }));
        quanLyThucDon_jPanel.add(searchMonAnTheo_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 190, 30));

        javax.swing.ImageIcon themMonAnIcon = new javax.swing.ImageIcon(getClass().getResource("/image/add_dishes.png"));
        java.awt.Image themMonAnImage = themMonAnIcon.getImage().getScaledInstance(20,20, java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon scaledThemMonAnIcon = new javax.swing.ImageIcon(themMonAnImage);
        themMonAn_jButton.setIcon(scaledThemMonAnIcon);
        themMonAn_jButton.setText("THÊM MÓN");
        themMonAn_jButton.setToolTipText("Thêm món ăn mới");
        themMonAn_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themMonAn_jButtonActionPerformed(evt);
            }
        });
        quanLyThucDon_jPanel.add(themMonAn_jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 150, 30));

        searchMonAn_jPanel.setLayout(new javax.swing.BoxLayout(searchMonAn_jPanel, javax.swing.BoxLayout.X_AXIS));

        searchMonAn_jTextField.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        searchMonAn_jTextField.setText("Search...");
        searchMonAn_jTextField.setName(""); // NOI18N
        searchMonAn_jTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchMonAn_jTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchMonAn_jTextFieldFocusLost(evt);
            }
        });
        searchMonAn_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMonAn_jTextFieldActionPerformed(evt);
            }
        });
        searchMonAn_jPanel.add(searchMonAn_jTextField);

        javax.swing.ImageIcon searchMonAnIcon = new javax.swing.ImageIcon(getClass().getResource("/image/search.png"));
        java.awt.Image searchMonAnImage = searchMonAnIcon.getImage().getScaledInstance(20,20, java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon scaledSearchMonAnIcon = new javax.swing.ImageIcon(searchMonAnImage);
        searchMonAn_jButton1.setIcon(scaledSearchMonAnIcon);
        searchMonAn_jButton1.setToolTipText("");
        searchMonAn_jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchMonAn_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMonAn_jButton1ActionPerformed(evt);
            }
        });
        searchMonAn_jPanel.add(searchMonAn_jButton1);

        quanLyThucDon_jPanel.add(searchMonAn_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 285, 30));

        themLoaiMonAn_jButton.setText("Thêm loại món ăn");
        themLoaiMonAn_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themLoaiMonAn_jButtonActionPerformed(evt);
            }
        });
        quanLyThucDon_jPanel.add(themLoaiMonAn_jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        suaLoaiMonAn_jButton.setText("Sửa loại món ăn");
        suaLoaiMonAn_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaLoaiMonAn_jButtonActionPerformed(evt);
            }
        });
        quanLyThucDon_jPanel.add(suaLoaiMonAn_jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 130, 30));
        quanLyThucDon_jPanel.add(showMonAn_jTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 730, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(quanLyThucDon_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(quanLyThucDon_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void showMonAnTuDataBase() {
        try {

            //Xet loai mon an va tao panel
            String sqlStatementTenLoaiMonAn = "select TENLMA from LOAIMONAN";
            ResultSet tenLoaiMonAnResultSet = ExcuteSQLStatement1.ExcuteSQLQuery(sqlStatementTenLoaiMonAn);
            String tenLoaiMonAn;
            while (tenLoaiMonAnResultSet.next()) {
                tenLoaiMonAn = tenLoaiMonAnResultSet.getString("TENLMA");
                JScrollPane monAn_jScrollPane = new JScrollPane();
                monAn_jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
                monAn_jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
                monAn_jScrollPane.setPreferredSize(new java.awt.Dimension(400, 612));
                JPanel monAn_jPanel = new javax.swing.JPanel();
                monAn_jPanel.setName(tenLoaiMonAn);
                monAn_jPanel.setLayout(new java.awt.GridLayout(0, 3));
                monAn_jScrollPane.setViewportView(monAn_jPanel);
                showMonAn_jTabbedPane.addTab(tenLoaiMonAn, monAn_jScrollPane);
                loaiMonAnJPanels.add(monAn_jPanel);
            }
            //Xet tung mon an va tao 1 button cho mon an do va gan vao panel
            String sqlStatement = "select * from monan";
            ResultSet monAnResultSet = ExcuteSQLStatement1.ExcuteSQLQuery(sqlStatement);
            while (monAnResultSet.next()) {
                //Lay ten nguyen lieu cua mon an
                String maMonAn = monAnResultSet.getString("MAMON");
                String sqlStatementMaNguyenLieu = "select MANL from CHEBIEN where MAMON = '" + maMonAn + "'";
                ResultSet maNguyenLieuResultSet = ExcuteSQLStatement1.ExcuteSQLQuery(sqlStatementMaNguyenLieu);
                while (maNguyenLieuResultSet.next()) {
                    String maNguyenLieu = maNguyenLieuResultSet.getString("MANL");
                    String sqlStatementTenNguyenLieu = "select TENNL from KHONGUYENLIEU where MANL = '" + maNguyenLieu + "'";
                    ResultSet tenNguyenLieuResultSet = ExcuteSQLStatement1.ExcuteSQLQuery(sqlStatementTenNguyenLieu);
                    while (tenNguyenLieuResultSet.next()) {
                        String tenNguyenLieu = tenNguyenLieuResultSet.getString("TENNL");
                        nguyenLieuDaChon.add(tenNguyenLieu);
                    }
                }
                //Lay link anh, ten mon, don gia
                String link_image = monAnResultSet.getString("LINK_IMAGE");
                String tenMon = monAnResultSet.getString("TENMON");
                int donGia = monAnResultSet.getInt("DONGIA");
                //Lay ma loai mon an (de lay ten mon an)
                String maLoaiMonAn = monAnResultSet.getString("MALOAIMONAN");
                String sqlStatement1 = "select TENLMA from LOAIMONAN where MALMA = '" + maLoaiMonAn + "'";
                ResultSet tenMonAnResultSet = ExcuteSQLStatement1.ExcuteSQLQuery(sqlStatement1);
                while (tenMonAnResultSet.next()) {
                    String tenloaiMonAn = tenMonAnResultSet.getString("TENLMA");
                    DishesButton1 newDishesButton = new DishesButton1(link_image, tenMon, tenloaiMonAn, maMonAn, donGia, nguyenLieuDaChon);
                    nguyenLieuDaChon.clear();
                    listMonAn.add(newDishesButton);
                    for (JPanel loaiMonAnJPanel : loaiMonAnJPanels) {
                        if (newDishesButton.getTenLoaiMonAn().equals(loaiMonAnJPanel.getName())) {
                            loaiMonAnJPanel.add(newDishesButton);
                        }
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public String[] chonThongTinLoaiMonAn(ArrayList<String> StrTenLMA) {
        try {
            String sql = "SELECT TENLMA FROM LOAIMONAN";
            ResultSet res = ExcuteSQLStatement1.ExcuteSQLQuery(sql);
            boolean flag_Trung = false;
            while (res.next()) {
                String TENLMA = res.getString("TENLMA");
                for (int i = 0; i < StrTenLMA.size(); i++) //CHECK TRÙNG TÊN LMA
                {
                    if (StrTenLMA.get(i).equals(TENLMA)) // NẾU TRÙNG THÌ FLAG = TRUE -> BỎ QUA, KHÔNG ADD NỮA
                    {
                        flag_Trung = true;
                        break;
                    }
                }

                if (!flag_Trung) // NẾU KHÔNG TRÙNG THÌ ADD
                {
                    StrTenLMA.add(TENLMA);
                }
            }
        } catch (SQLException | HeadlessException ex) {
            System.out.println("the error is" + ex);
        }
        Object[] arr = StrTenLMA.toArray();
        String[] str = Arrays.copyOf(arr, arr.length, String[].class);
        return str;
    }

    public String[] chonTenNguyenLieu(ArrayList<String> StrTenNL) {
        try {
            String sql = "SELECT TENNL FROM KHONGUYENLIEU";
            ResultSet res = ExcuteSQLStatement1.ExcuteSQLQuery(sql);
            boolean flag_Trung = false;
            while (res.next()) {
                String TENNL = res.getString("TENNL");
                for (int i = 0; i < StrTenNL.size(); i++) //CHECK TRÙNG TÊN LMA
                {
                    if (StrTenNL.get(i).equals(TENNL)) // NẾU TRÙNG THÌ FLAG = TRUE -> BỎ QUA, KHÔNG ADD NỮA
                    {
                        flag_Trung = true;
                        break;
                    }
                }

                if (!flag_Trung) // NẾU KHÔNG TRÙNG THÌ ADD
                {
                    StrTenNL.add(TENNL);
                }
            }
        } catch (SQLException | HeadlessException ex) {
            System.out.println("the error is" + ex);
        }
        Object[] arr = StrTenNL.toArray();
        String[] str = Arrays.copyOf(arr, arr.length, String[].class);
        return str;
    }

    public void setThemMonAnJDialogVeTrangThaiBanDau() {
        themMaMonAn_jTextField.setText("");
        themTenMonAn_jTextField.setText("");
        themPathAnhMonAn_jTextField.setText("Path...");
        themLoaiMonAn_jComboBox.setSelectedIndex(0);
        themDonGia_jTextField.setText("0");
        nguyenLieuDaChon.clear();
    }

    public void setThemLoaiMonAnJDialogVeTrangThaiBanDau() {
        themTenLoaiMonAn_jTextField.setText("");
        themMoTaLoaiMonAn_jTextArea.setText("");
    }


    private void themMonAn_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themMonAn_jButtonActionPerformed
        // TODO add your handling code here:
        setThemMonAnJDialogVeTrangThaiBanDau();
        themMonAn_jDialog.pack();
        themMonAn_jDialog.setLocationRelativeTo(null);
        themMonAn_jDialog.setVisible(true);
    }//GEN-LAST:event_themMonAn_jButtonActionPerformed

    private void searchMonAn_jTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchMonAn_jTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMonAn_jTextFieldFocusGained

    private void searchMonAn_jTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchMonAn_jTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMonAn_jTextFieldFocusLost

    private void searchMonAn_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMonAn_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMonAn_jTextFieldActionPerformed

    private void searchMonAn_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMonAn_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMonAn_jButton1ActionPerformed

    private void cancel_themMonAn_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_themMonAn_jButtonActionPerformed
        // TODO add your handling code here:
        setThemMonAnJDialogVeTrangThaiBanDau();
        themMonAn_jDialog.setVisible(false);
    }//GEN-LAST:event_cancel_themMonAn_jButtonActionPerformed

    private void confirmThemMonAn_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmThemMonAn_jButtonActionPerformed
        // TODO add your handling code here:
        String link_img = themPathAnhMonAn_jTextField.getText();
        String tenMon = themTenMonAn_jTextField.getText();
        Object tenLoaiMonAn = themLoaiMonAn_jComboBox.getSelectedItem();
        String maMonAn = themMaMonAn_jTextField.getText();
        int donGia;
        try {
            donGia = Integer.parseInt(themDonGia_jTextField.getText());
        } catch (NumberFormatException e) {
            donGia = 0;
        }
        DishesButton1 newDishesButton = new DishesButton1(link_img, tenMon, tenLoaiMonAn, maMonAn, donGia, nguyenLieuDaChon);
        for (JPanel loaiMonAnJPanel : loaiMonAnJPanels) {
            if (newDishesButton.getTenLoaiMonAn().equals(loaiMonAnJPanel.getName())) {
                loaiMonAnJPanel.add(newDishesButton);
            }
        }
        themMonAn_jDialog.setVisible(false);
        String sql = "SELECT MALMA FROM LOAIMONAN where TENLMA ='" + tenLoaiMonAn.toString() + "'";
        ResultSet loaiMonAnResultSet = ExcuteSQLStatement1.ExcuteSQLQuery(sql);
        String maLoaiMonAn;
        try {
            while (loaiMonAnResultSet.next()) {
                maLoaiMonAn = loaiMonAnResultSet.getString("MALMA");
                String sqlStatementUpdateMonAn = "insert into MONAN values('" + maMonAn + "','" + tenMon + "','" + link_img + "','" + maLoaiMonAn + "'," + donGia + ")";
                System.out.println(sqlStatementUpdateMonAn);
                ExcuteSQLStatement1.ExcuteSQLUpdate(sqlStatementUpdateMonAn);
                confirmThemMonAn_jOptionPane.showMessageDialog(quanLyThucDon_jPanel, "Them mon an thanh cong!");
                ResultSet test = ExcuteSQLStatement1.ExcuteSQLQuery("select * from MONAN");
                while(test.next())
                {
                    System.out.println(test.getString("TENMON"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyThucDonJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        setThemMonAnJDialogVeTrangThaiBanDau();
    }//GEN-LAST:event_confirmThemMonAn_jButtonActionPerformed

    private void themTenMonAn_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themTenMonAn_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_themTenMonAn_jTextFieldActionPerformed

    private void themAnhMonAnTuFile_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themAnhMonAnTuFile_jButtonActionPerformed
        // TODO add your handling code here:
        themMonAn_jFileChooser.showOpenDialog(null);
        File anhMonAn = themMonAn_jFileChooser.getSelectedFile();
        String link_image = anhMonAn.getAbsolutePath();
        themPathAnhMonAn_jTextField.setText(link_image);

    }//GEN-LAST:event_themAnhMonAnTuFile_jButtonActionPerformed

    private void confirmSuaMonAn_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmSuaMonAn_jButtonActionPerformed
        // TODO add your handling code here:
        int x = xoa_suaMonAn_jOptionPane.showOptionDialog(quanLyThucDon_jPanel, "Bạn có chắc muốn sửa món ăn?", "Cảnh báo xác nhận sửa món ăn", 0, 2, null, null, null);
        if (x == JOptionPane.YES_OPTION) {
            trangThaiChonXoaOrSua = 2;
            xoa_suaMonAn_jDialog.setVisible(false);
        }
    }//GEN-LAST:event_confirmSuaMonAn_jButtonActionPerformed

    private void cancel_xoa_suaMonAn_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_xoa_suaMonAn_jButtonActionPerformed
        // TODO add your handling code here:
        trangThaiChonXoaOrSua = 0;
        xoa_suaMonAn_jDialog.setVisible(false);
    }//GEN-LAST:event_cancel_xoa_suaMonAn_jButtonActionPerformed

    private void confirmXoaMonAn_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmXoaMonAn_jButtonActionPerformed
        // TODO add your handling code here:
        trangThaiChonXoaOrSua = 1;
        xoa_suaMonAn_jDialog.setVisible(false);
    }//GEN-LAST:event_confirmXoaMonAn_jButtonActionPerformed

    private void suaAnhMonAnTuFile_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaAnhMonAnTuFile_jButtonActionPerformed
        // TODO add your handling code here:
        themMonAn_jFileChooser.showOpenDialog(null);
        File anhMonAn = themMonAn_jFileChooser.getSelectedFile();
        String link_image = anhMonAn.getAbsolutePath();
        suaPathAnhMonAn_jTextField.setText(link_image);
    }//GEN-LAST:event_suaAnhMonAnTuFile_jButtonActionPerformed

    private void themLoaiMonAn_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themLoaiMonAn_jButtonActionPerformed
        // TODO add your handling code here:
        themLoaiMonAn_jDialog.pack();
        themLoaiMonAn_jDialog.setLocationRelativeTo(null);
        themLoaiMonAn_jDialog.setVisible(true);
    }//GEN-LAST:event_themLoaiMonAn_jButtonActionPerformed

    private void confirmThemNguyenLieu_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmThemNguyenLieu_jButtonActionPerformed
        // TODO add your handling code here:
        if (!themShowNguyenLieuDaChon_jTextArea.getText().contains(themNguyenLieu_jList.getSelectedValue()))
        {
            if (themShowNguyenLieuDaChon_jTextArea.getText().equals(""))
            themShowNguyenLieuDaChon_jTextArea.setText(themNguyenLieu_jList.getSelectedValue());
            else themShowNguyenLieuDaChon_jTextArea.setText(themShowNguyenLieuDaChon_jTextArea.getText() + ", " + themNguyenLieu_jList.getSelectedValue() );
        }
        nguyenLieuDaChon.add(themNguyenLieu_jList.getSelectedValue());
        
    }//GEN-LAST:event_confirmThemNguyenLieu_jButtonActionPerformed

    private void confirmSuaNguyenLieu_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmSuaNguyenLieu_jButtonActionPerformed
        trangThaiChonXoaOrSua = 2;
    }//GEN-LAST:event_confirmSuaNguyenLieu_jButtonActionPerformed

    private void suaLoaiMonAn_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaLoaiMonAn_jButtonActionPerformed
        // TODO add your handling code here:
        suaLoaiMonAn_jDialog.pack();
        suaLoaiMonAn_jDialog.setLocationRelativeTo(null);
        suaLoaiMonAn_jDialog.setVisible(true);
    }//GEN-LAST:event_suaLoaiMonAn_jButtonActionPerformed

    private void confirmThemLoaiMonAn_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmThemLoaiMonAn_jButtonActionPerformed
        // TODO add your handling code here:
        JScrollPane monAn_jScrollPane = new JScrollPane();
        monAn_jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        monAn_jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        monAn_jScrollPane.setPreferredSize(new java.awt.Dimension(400, 612));
        JPanel monAn_jPanel = new javax.swing.JPanel();
        monAn_jPanel.setLayout(new java.awt.GridLayout(0, 3));
        monAn_jScrollPane.setViewportView(monAn_jPanel);
        showMonAn_jTabbedPane.addTab(themTenLoaiMonAn_jTextField.getText(), monAn_jScrollPane);
        confirmThemMonAn_jOptionPane.showMessageDialog(quanLyThucDon_jPanel, "Thêm loại món ăn thành công!");
        loaiMonAnJPanels.add(monAn_jPanel);
        setThemLoaiMonAnJDialogVeTrangThaiBanDau();
        themLoaiMonAn_jDialog.setVisible(false);
    }//GEN-LAST:event_confirmThemLoaiMonAn_jButtonActionPerformed

    private void cancelThemLoaiMonAn_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelThemLoaiMonAn_jButtonActionPerformed
        // TODO add your handling code here:
        setThemLoaiMonAnJDialogVeTrangThaiBanDau();
        themLoaiMonAn_jDialog.setVisible(false);
    }//GEN-LAST:event_cancelThemLoaiMonAn_jButtonActionPerformed

    private void comfirmSuaLoaiMonAn_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comfirmSuaLoaiMonAn_jButtonActionPerformed
        // TODO add your handling code here:
        suaLoaiMonAn_jDialog.setVisible(false);
        reloadGUIMonAn();
    }//GEN-LAST:event_comfirmSuaLoaiMonAn_jButtonActionPerformed
    private void reloadGUIMonAn() {
        showMonAn_jTabbedPane.removeAll();
        showMonAn_jTabbedPane.revalidate();
        showMonAn_jTabbedPane.repaint();
        showMonAnTuDataBase();
    }
    private void chonMonAnCanSua_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonMonAnCanSua_jButtonActionPerformed
        // TODO add your handling code here:
        String tenLoaiMonAnCanSua = suaLoaiMonAn_jComboBox.getSelectedItem().toString();
        tenMoiLoaiMonAn_jTextField.setText(tenLoaiMonAnCanSua);
        String sqlStatementMoTaLoaiMonAn = "select MOTA from LOAIMONAN where TENLMA ='" + tenLoaiMonAnCanSua + "'";
        ResultSet moTaLoaiMonAnCanSuaResultSet = ExcuteSQLStatement1.ExcuteSQLQuery(sqlStatementMoTaLoaiMonAn);
        try {
            while (moTaLoaiMonAnCanSuaResultSet.next()) {
                moTaMoiLoaiMonAn_jTextArea.setText(moTaLoaiMonAnCanSuaResultSet.getString("MOTA"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyThucDonJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_chonMonAnCanSua_jButtonActionPerformed

    private void cancelSuaLoaiMonAn_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSuaLoaiMonAn_jButtonActionPerformed
        // TODO add your handling code here:
        setSuaLoaiMonAnDialogVeTrangThaiBanDau();
        suaLoaiMonAn_jDialog.setVisible(false);

    }//GEN-LAST:event_cancelSuaLoaiMonAn_jButtonActionPerformed
    private void setSuaLoaiMonAnDialogVeTrangThaiBanDau() {
        suaLoaiMonAn_jComboBox.setSelectedIndex(0);
        tenMoiLoaiMonAn_jTextField.setText("");
        moTaMoiLoaiMonAn_jTextArea.setText("");
    }

    private void confirmXoaNguyenLieu_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmXoaNguyenLieu_jButtonActionPerformed
        // TODO add your handling code here:
        String[] temp = suaShowNguyenLieu_jTextArea.getText().split("[\\n]");
        nguyenLieuSua = new ArrayList<>(Arrays.asList(temp));
        if (suaShowNguyenLieu_jTextArea.getText().contains(suaNguyenLieu_jList.getSelectedValue() + "\\n")) {
            suaShowNguyenLieu_jTextArea.setText(suaShowNguyenLieu_jTextArea.getText().replace(suaNguyenLieu_jList.getSelectedValue() + "\\n", ""));
        } else if (suaShowNguyenLieu_jTextArea.getText().contains(suaNguyenLieu_jList.getSelectedValue())) {
            suaShowNguyenLieu_jTextArea.setText(suaShowNguyenLieu_jTextArea.getText().replace(suaNguyenLieu_jList.getSelectedValue(), ""));
        }
        nguyenLieuSua.remove(suaNguyenLieu_jList.getSelectedValue());
        
    }//GEN-LAST:event_confirmXoaNguyenLieu_jButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelSuaLoaiMonAn_jButton;
    private javax.swing.JButton cancelThemLoaiMonAn_jButton;
    private javax.swing.JButton cancel_themMonAn_jButton;
    private javax.swing.JButton cancel_xoa_suaMonAn_jButton;
    private javax.swing.JButton chonMonAnCanSua_jButton;
    private javax.swing.JButton comfirmSuaLoaiMonAn_jButton;
    public static javax.swing.JButton confirmSuaMonAn_jButton;
    private javax.swing.JButton confirmSuaNguyenLieu_jButton;
    private javax.swing.JButton confirmThemLoaiMonAn_jButton;
    private javax.swing.JButton confirmThemMonAn_jButton;
    private javax.swing.JOptionPane confirmThemMonAn_jOptionPane;
    private javax.swing.JButton confirmThemNguyenLieu_jButton;
    private javax.swing.JButton confirmXoaNguyenLieu_jButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel moTaMoiLoaiMonAn_jLabel;
    private javax.swing.JTextArea moTaMoiLoaiMonAn_jTextArea;
    private javax.swing.JPanel quanLyThucDon_jPanel;
    private javax.swing.JComboBox<String> searchMonAnTheo_jComboBox;
    private javax.swing.JButton searchMonAn_jButton1;
    private javax.swing.JPanel searchMonAn_jPanel;
    private javax.swing.JTextField searchMonAn_jTextField;
    private javax.swing.JTabbedPane showMonAn_jTabbedPane;
    private javax.swing.JButton suaAnhMonAnTuFile_jButton;
    private javax.swing.JLabel suaAnhMonAn_jLabel;
    private javax.swing.JComboBox<String> suaChonLoaiMonAn_jComboBox;
    private javax.swing.JLabel suaChonLoaiMonAn_jLabel;
    private javax.swing.JLabel suaDonGia_jLabel;
    public static javax.swing.JTextField suaDonGia_jTextField;
    private javax.swing.JButton suaLoaiMonAn_jButton;
    public static javax.swing.JComboBox<String> suaLoaiMonAn_jComboBox;
    private javax.swing.JDialog suaLoaiMonAn_jDialog;
    private javax.swing.JLabel suaLoaiMonAn_jLabel;
    private javax.swing.JLabel suaMaMonAn_jLabel;
    public static javax.swing.JTextField suaMaMonAn_jTextField;
    private javax.swing.JLabel suaNguyenLieu_jLabel;
    public static javax.swing.JList<String> suaNguyenLieu_jList;
    public static javax.swing.JTextField suaPathAnhMonAn_jTextField;
    public static javax.swing.JTextArea suaShowNguyenLieu_jTextArea;
    public static javax.swing.JTextField suaTenMonAn_jTextField;
    private javax.swing.JLabel suaTenMon_jLabel;
    public static javax.swing.JComboBox<String> suaTinhTrangMonAn_jComboBox;
    private javax.swing.JLabel suaTinhTrangMonAn_jLabel;
    private javax.swing.JLabel tenMoiLoaiMonAn_jLabel;
    private javax.swing.JLabel tenMoiLoaiMonAn_jLabel1;
    private javax.swing.JTextField tenMoiLoaiMonAn_jTextField;
    private javax.swing.JButton themAnhMonAnTuFile_jButton;
    private javax.swing.JLabel themAnhMonAn_jLabel;
    private javax.swing.JLabel themDonGia_jLabel;
    private javax.swing.JTextField themDonGia_jTextField;
    private javax.swing.JButton themLoaiMonAn_jButton;
    private javax.swing.JComboBox<String> themLoaiMonAn_jComboBox;
    private javax.swing.JDialog themLoaiMonAn_jDialog;
    private javax.swing.JLabel themLoaiMonAn_jLabel;
    private javax.swing.JTextField themMaMonAn_jTextField;
    private javax.swing.JLabel themMaMonaAn_jLabel;
    private javax.swing.JLabel themMoTaLoaiMonAn_jLabel;
    public static javax.swing.JTextArea themMoTaLoaiMonAn_jTextArea;
    private javax.swing.JButton themMonAn_jButton;
    private javax.swing.JDialog themMonAn_jDialog;
    private javax.swing.JFileChooser themMonAn_jFileChooser;
    private javax.swing.JList<String> themNguyenLieu_jList;
    private javax.swing.JTextField themPathAnhMonAn_jTextField;
    private javax.swing.JTextArea themShowNguyenLieuDaChon_jTextArea;
    private javax.swing.JLabel themTenLoaiMonAn_jLabel;
    public static javax.swing.JTextField themTenLoaiMonAn_jTextField;
    private javax.swing.JTextField themTenMonAn_jTextField;
    private javax.swing.JLabel themTenMon_jLabel;
    public static javax.swing.JDialog xoa_suaMonAn_jDialog;
    private javax.swing.JOptionPane xoa_suaMonAn_jOptionPane;
    // End of variables declaration//GEN-END:variables
}
